releases:
- name: kafka-prod
  namespace: prod
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 25.3.5
  set:
  - name: controller.replicaCount
    value: 5
  - name: listeners.client.protocol
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol
    value: SASL_PLAINTEXT
- name: kafka-dev
  namespace: dev
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 32.2.8
  set:
  - name: controller.replicaCount
    value: 1
  - name: listeners.client.protocol
    value: PLAINTEXT
  - name: listeners.interbroker.protocol
    value: PLAINTEXT