apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: you_access_key
  secretAccessKey: you_secret_key
  endpoint: https://storage.yandexcloud.net
