apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: git@github.com:Kuber-2025-04OTUS/kvlaznev_repo.git
    targetRevision: kubernetes-networks
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework