apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-sm
  namespace: default
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - homework 
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: nginx-exporter
    interval: 30s
