apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crb_cd_admin
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io