apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-web
  namespace: {{.Values.namespace}}
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: /homework($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{.Release.Name}}-web
            port:
              number: {{.Values.service.targetPort}}
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: {{.Release.Name}}-web
            port:
              number: {{.Values.service.targetPort}}
