apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc
  namespace: {{.Values.namespace}}  
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: minikube-hostpath