apiVersion: v1                                                                                                                                        
kind: ServiceAccount                                                                                                                                  
metadata:                                                                                                                                             
  name: sa
  namespace: {{.Values.namespace}}