apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa_binding
subjects:
  - kind: ServiceAccount
    name: sa
    namespace: homework
roleRef:
  kind: ClusterRole
  name: cr_sa
  apiGroup: rbac.authorization.k8s.io