apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: sa
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - name: nginx
        image: nginx-8000:1.27.5
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: workdir
          mountPath: /homework
        - name: workfile
          mountPath: /homework/conf
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm -f /homework/index.html"]
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/index.html"
            port: 8000
      initContainers:
      - name: wget-index
        image: busybox:1.35
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      - name: wget-metrics
        image: busybox:1.35
        command:
         - sh
         - '-c'
         - >
           TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
           wget --no-check-certificate --header="Authorization: Bearer ${TOKEN}" \
             --output-document=/init/metrics.html https://kubernetes.default.svc/metrics
        volumeMounts:
        - name: workdir
          mountPath: "/init"             
      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: pvc-sc
      - name: workfile
        configMap:
          name: conf-map
          items:
          - key: "file"
            path: "file" 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1