apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx-8000:1.27.5
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm -f /homework/index.html"]      
  initContainers:
  - name: wget
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}